# Generated by Django 4.0.5 on 2022-08-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_group_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='standing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
