# Generated by Django 4.0.5 on 2022-08-31 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_match_time_standing_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sports.team'),
        ),
    ]
