# Generated by Django 4.0.5 on 2022-08-31 04:36

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_address_profile_gender_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.file_upload_directory),
        ),
    ]
